name: Publish Storybook PR
on:
  pull_request:
    types: [opened, reopened]
    branches-ignore:
      - master
  push:
    branches-ignore:
      - master
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: storybook-static # change to your build folder
          install_command: yarn install
          build_command: npm run build-storybook -- -o ./storybook-static
